// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zwsaxgedqgmozetdqzyc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp3c2F4Z2VkcWdtb3pldGRxenljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MDY5MjAsImV4cCI6MjA2NDE4MjkyMH0.Uz19r4GqrXMEHfBY1fVoQyNQv8sdoSTGRKa73Xbg364";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);